package org.notima.businessobjects.adapter.tools.command;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;
import java.util.Properties;

import javax.xml.bind.JAXB;

import org.apache.karaf.shell.api.action.Argument;
import org.apache.karaf.shell.api.action.Command;
import org.apache.karaf.shell.api.action.Completion;
import org.apache.karaf.shell.api.action.Option;
import org.apache.karaf.shell.api.action.lifecycle.Reference;
import org.apache.karaf.shell.api.action.lifecycle.Service;
import org.apache.karaf.shell.api.console.Session;
import org.apache.karaf.shell.support.completers.FileCompleter;
import org.notima.businessobjects.adapter.tools.EmailInvoiceDelivery;
import org.notima.businessobjects.adapter.tools.FormatterFactory;
import org.notima.businessobjects.adapter.tools.InvoiceDeliveryMethodFactory;
import org.notima.businessobjects.adapter.tools.InvoiceFormatter;
import org.notima.generic.businessobjects.BusinessPartner;
import org.notima.generic.businessobjects.Invoice;
import org.notima.generic.businessobjects.InvoiceList;
import org.notima.generic.businessobjects.exception.NoSuchTenantException;
import org.notima.util.json.JsonUtil;
import org.notima.generic.ifacebusinessobjects.InvoiceDeliveryBatch;
import org.notima.generic.ifacebusinessobjects.InvoiceDeliveryMethod;

@Command(scope = "notima", name = "print-invoices", description = "Prints invoices from a file (can be generated by read-invoices) and optionally delivers them, ie by e-mail or as e-invoices")
@Service
public class PrintInvoices extends AbstractAction {
	
	@Reference 
	Session sess;
	
	@Reference
	private FormatterFactory	formatterFactory;
	
	@Reference
	private InvoiceDeliveryMethodFactory deliveryMethodFactory;
    
    @Option(name = "-format", aliases = { "--format" }, description = "Output format, ie pdf or peppol. Default is the delivery method's format, or pdf", required = false, multiValued = false)
	private String				format;
	
	private InvoiceFormatter	formatter;
	
    @Option(name="-s", description="Sends invoices by e-mail if applicable. Same as --delivery email", required = false, multiValued = false)
    private boolean	sendByEmail;

    @Option(name="--delivery", description="Delivers the invoices using this delivery method, ie email or ekopost", required = false, multiValued = false)
    private String	deliveryType;

    @Option(name="-a", description="If set, all e-mails go to this address", required = false, multiValued = false)
    private String	recipientAddress;
    
    @Option(name = "-e", aliases = { "--encrypt" }, description = "Send encrypted email.", required = false, multiValued = false)
    private boolean encrypt;
    
    @Option(name="-od", description="Output directory (where files are placed)", required = false, multiValued = false)
    private String	outputDirectory;
    
	@Argument(index = 0, name = "fileName", description ="File with invoice information", required = true, multiValued = false)
	@Completion(FileCompleter.class)   
	private String invoiceFile = "";
	
	private InvoiceList invoiceList = null;
	private Properties props = new Properties();
	
	private InvoiceDeliveryMethod deliveryMethod;
	private InvoiceDeliveryBatch deliveryBatch;
	
	@Override
	protected Object onExecute() throws Exception {
		
		initDeliveryMethod();
		initFormatterFactory();
		parseOptions();

		printInvoices();
		
		return null;
	}
	
	private void initDeliveryMethod() throws Exception {
		
		if (sendByEmail && deliveryType==null) {
			deliveryType = EmailInvoiceDelivery.TYPE;
		}
		if (deliveryType==null) return;
		
		deliveryMethod = deliveryMethodFactory.getInvoiceDeliveryMethod(deliveryType);
		if (deliveryMethod==null) {
			throw new Exception("No delivery method " + deliveryType + ". Available: " + deliveryMethodFactory.getInvoiceDeliveryTypes());
		}
		if (format==null) {
			format = deliveryMethod.getDefaultFormat();
		}
	}
	
	private void initFormatterFactory() throws Exception {

		if (format==null) {
			format = "pdf";
		}

		formatter = formatterFactory.getInvoiceFormatter(format);
		if (formatter==null) {
			throw new Exception("No invoice formatter for format " + format + ". Is the adapter providing it installed?");
		}
		
	}
	
	private void parseOptions() throws ParseException, NoSuchTenantException, Exception {

		parseInvoiceFile();
		
		props.setProperty("JasperFile", 
				"/home/daniel/develop/notima-workspace/businessObjectAdapters/jasperReportAdapter/src/main/resources/reports/InvoiceBasic.jasper");
		
		if (outputDirectory==null) {
			outputDirectory = new File(invoiceFile).getAbsoluteFile().getParent();
		}
		
		props.setProperty("JasperOutputDir", outputDirectory);
		props.setProperty(InvoiceFormatter.OUTPUT_DIR, outputDirectory);
		
		if (deliveryMethod!=null) {
			Properties deliveryProps = new Properties();
			if (recipientAddress!=null) {
				deliveryProps.setProperty(EmailInvoiceDelivery.RECIPIENT_ADDRESS, recipientAddress);
			}
			deliveryProps.setProperty(EmailInvoiceDelivery.ENCRYPT, Boolean.toString(encrypt));
			deliveryBatch = deliveryMethod.startBatch(invoiceList, deliveryProps);
		}
	}
	
	
	private void printInvoices() throws Exception {
		
		List<Invoice<?>> invoices = invoiceList.getInvoiceList();
		
		for (Invoice<?> ii : invoices) {
			printInvoice(ii);
		}
		
		if (deliveryBatch!=null) {
			int sent = deliveryBatch.complete();
			sess.getConsole().println(sent + " of " + invoices.size() + " invoice(s) delivered by " + deliveryMethod.getType());
		}
		
	}
	
	private void printInvoice(Invoice<?> invoice) throws Exception {
		
		// jasperLang = props.getProperty(JASPER_LANG);
		
		String outputFilename = getFileNameForInvoice(invoice);
		
		props.setProperty("JasperOutputFilename", outputFilename);
		props.setProperty(InvoiceFormatter.OUTPUT_FILENAME, outputFilename);
		
		addCreditorPaymentInformation(invoice);
		
		String path = formatter.formatInvoice(invoice, format, props);
		sess.getConsole().println(path);
		
		if (deliveryBatch!=null) {
			String result = deliveryBatch.deliver(invoice, new File(path));
			sess.getConsole().println("  " + invoice.getDocumentKey() + ": " 
					+ (result!=null ? result : "not delivered by " + deliveryMethod.getType()));
		}
		
	}
	
	/**
	 * Puts the creditor on the invoice, since the formatter only gets the invoice.
	 * If the invoice has no sender, the creditor is used as sender. Otherwise the
	 * creditor's payment information (if any) is copied as a whole to the sender.
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	private void addCreditorPaymentInformation(Invoice invoice) {
		
		BusinessPartner<?> creditor = invoiceList.getCreditor();
		if (creditor==null) return;
		
		BusinessPartner sender = invoice.getSender();
		if (sender==null) {
			invoice.setSender(creditor);
			return;
		}
		if (!hasPaymentInformation(creditor)) return;
		sender.setRemitToAccount(creditor.getRemitToAccount());
		sender.setRemitToAccountType(creditor.getRemitToAccountType());
		sender.setRemitToIBAN(creditor.getRemitToIBAN());
		sender.setRemitToBIC(creditor.getRemitToBIC());
	}
	
	private boolean hasPaymentInformation(BusinessPartner<?> bp) {
		return (bp.getRemitToAccount() != null && bp.getRemitToAccount().trim().length() > 0)
				|| (bp.getRemitToIBAN() != null && bp.getRemitToIBAN().trim().length() > 0);
	}
	
	private String getFileNameForInvoice(Invoice<?> invoice) {
		
		StringBuffer buf = new StringBuffer();
		buf.append(invoice.getDocumentKey());
		String email = invoice.getBillEmail();
		if (email!=null && invoice.getBusinessPartner().isEmailInvoice()) {
			buf.append("-email");
		}

		return buf.toString();
	}
	
	
	private void parseInvoiceFile() throws IOException {

		if (invoiceFile.toLowerCase().endsWith("xml")) {
			parseInvoiceXMLFile();
		}
		if (invoiceFile.toLowerCase().endsWith("json")) {
			parseInvoiceJsonFile();
		}
		
	}
	
	private void parseInvoiceJsonFile() throws IOException {
		
		FileReader fis = new FileReader(invoiceFile);
		invoiceList = JsonUtil.buildGson().fromJson(fis, InvoiceList.class);
		fis.close();
		
	}
	
	private void parseInvoiceXMLFile() throws IOException {
		
		FileInputStream fis = new FileInputStream(invoiceFile);
		invoiceList = JAXB.unmarshal(fis, InvoiceList.class);
		fis.close();
		File f = new File(invoiceFile);
		System.setProperty("INVOICELIST_XML_FILE", f.getAbsolutePath());
		
	}

}
